### ISSUE TITLE
Bug no envio de dados da tela "nf-form.jsp"

### ISSUE THREAD

**Issue by hygorp** [ggabriell455/SmallRoad-Web#1]
Retornando erro gigantesco ao clicar em Submit, fiz alterações de front-end, mas não alterei as funcionalidade, apenas atribuí classes do framework css, antes da reportação da Issue não fiz upload, testei primeiro o arquivos sem alterações do front-end, portanto, segue abaixo prints em ordem de tempo, do erro sem o front-end e com o front-end. Att.

![print01](https://cloud.githubusercontent.com/assets/16942121/26814184/eceb79c6-4a59-11e7-9056-458d1b2eb8e5.png)
![print02](https://cloud.githubusercontent.com/assets/16942121/26814186/ecefe678-4a59-11e7-9618-ea4c45612c87.png)
![print03](https://cloud.githubusercontent.com/assets/16942121/26814187/ecf3d378-4a59-11e7-9039-b7f1ff7fcae5.png)
![print04](https://cloud.githubusercontent.com/assets/16942121/26814185/ecee4458-4a59-11e7-892b-e98714526b89.png)

**Comment by rodrigodoe** [comment]
Corrigido, existia uma coluna no banco que estava setada como não nula, porem o valor que estava sendo passado no formulário era nulo, setei o script do sql pra aceitar esse campo como nulo. Por favor rodar ele novamente.
