### ISSUE TITLE
ERRO  GRAVE - Cadasto de Nota fiscal 

### ISSUE THREAD

**Issue by ggabriell455** [ggabriell455/SmallRoad-Web#14]
Apos preencher os campos, e clicar em "salvar" estoura um erro.

**Comment by rodrigodoe** [comment]
O problema esta ocorrendo pq o formulario que valida esta com uma expressao regular no qual tem um "-" é necessario que quando o usuario entre com o input o formulario remova o - pois o campo é um inteiro e n aceita tal expressao regular

**Comment by rodrigodoe** [comment]
foi corrigio o problema, os campos ja estao adequados para receberam a entrada do input
