### ISSUE TITLE
Tela de roteiro - CR00005

### ISSUE THREAD

**Issue by ggabriell455** [ggabriell455/SmallRoad-Web#15]
Múltiplos erros na tela de roteiro, segue lista:

- Quando tentamos apagar um roteiro dá "erro 404"
- Quando tentamos da "erro 404"
- Os campos de busca e acionar roteiro quando clicamos em cadastrar roteiro, estão invertidos, o campo de busca aparece pra cadastro e o pra cadastro em busca,

**Comment by hygorp** [comment]
Resolvido
