### ISSUE TITLE
Botão de Homer

### ISSUE THREAD

**Issue by ggabriell455** [ggabriell455/SmallRoad-Web#6]
Caso clique no botão de "Homer" já estando da tela de homer, estoura um erro 404, onde deveria não fazer nada, ou apenas reentrar na tela para atualiza-la.

Erro dado:

HTTP Status 404 - /home.jsp

type Status report

message /home.jsp

description The requested resource is not available.

Apache Tomcat/8.0.43

**Comment by rodrigodoe** [comment]
Corrigido, a pagina estava com o mapeamento erro no controller errado, as alterações necessárias foram feitas
